server:
  port: 8083

spring:
  application:
    name: streams-application

  kafka:
    bootstrap-servers: localhost:9092

    streams:
      application-id: ${spring.application.name}
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      # This setting is here to don't wait until the buffer is full
      cache-max-size-buffering: 0
      properties:
        schema.registry.url: http://localhost:8081
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        # LogAndFailExceptionHandler is the default!
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler

  sleuth:
    sampler:
      probability: 1.0

# Open up all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always