spring:
  application:
    name: producer-application

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      client-id: ${spring.application.name}
      properties:
        enable.idempotence: true

    properties:
      schema.registry.url: http://localhost:8081

  sleuth:
    sampler:
      probability: 1.0
# Open up all Spring Boot Actuator endpoints
management:

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
      env: local

